-- Supabase schema for deployed Worker Test Studio result collection.
-- Run this in the Supabase SQL editor before deploying the app.

create table if not exists public.tasks (
  id text primary key,
  title text not null default '',
  category text not null default '',
  reward text not null default '',
  time_limit_minutes text not null default '',
  description text not null default '',
  before_text text not null default '',
  after_text text not null default '',
  payload jsonb not null default '{}'::jsonb,
  created_at timestamptz not null default now(),
  updated_at timestamptz not null default now()
);

create table if not exists public.results (
  id bigint generated by default as identity primary key,
  task_id text references public.tasks(id) on delete set null,
  payload jsonb not null default '{}'::jsonb,
  created_at timestamptz not null default now()
);

create index if not exists idx_results_task_id on public.results(task_id);
create index if not exists idx_results_created_at on public.results(created_at desc);

alter table public.tasks enable row level security;
alter table public.results enable row level security;

-- The app's serverless API uses SUPABASE_SERVICE_ROLE_KEY, which bypasses RLS.
-- Do not expose the service role key in client-side JavaScript.
